#include "illuminate.hpp"

TEST_CASE(ASSERT_NEAR_ABS_UNLABELED) {
    ASSERT_NEAR_ABS_UNLABELED(1,1,1)
    ASSERT_NEAR_ABS_UNLABELED(1,2,1)
    ASSERT_NEAR_ABS_UNLABELED(1,3,1)
    ASSERT_NEAR_ABS_UNLABELED(1,4,1)
}
