#include "illuminate.hpp"

TEST_CASE(EXPECT_NEAR_ABS_UNLABELED) {
    EXPECT_NEAR_ABS_UNLABELED(1,1,1)
    EXPECT_NEAR_ABS_UNLABELED(1,2,1)
    EXPECT_NEAR_ABS_UNLABELED(1,3,1)
    EXPECT_NEAR_ABS_UNLABELED(1,4,1)
}
